/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as BeginnerRouteImport } from './routes/beginner'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProGsocRouteImport } from './routes/pro/gsoc'
import { Route as BeginnerPythonRouteImport } from './routes/beginner/python'
import { Route as BeginnerGithubRouteImport } from './routes/beginner/github'
import { Route as AdvancedDsaRouteImport } from './routes/advanced/dsa'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnerRoute = BeginnerRouteImport.update({
  id: '/beginner',
  path: '/beginner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProGsocRoute = ProGsocRouteImport.update({
  id: '/gsoc',
  path: '/gsoc',
  getParentRoute: () => ProRoute,
} as any)
const BeginnerPythonRoute = BeginnerPythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => BeginnerRoute,
} as any)
const BeginnerGithubRoute = BeginnerGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => BeginnerRoute,
} as any)
const AdvancedDsaRoute = AdvancedDsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => AdvancedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRouteWithChildren
  '/beginner': typeof BeginnerRouteWithChildren
  '/journey': typeof JourneyRoute
  '/pro': typeof ProRouteWithChildren
  '/advanced/dsa': typeof AdvancedDsaRoute
  '/beginner/github': typeof BeginnerGithubRoute
  '/beginner/python': typeof BeginnerPythonRoute
  '/pro/gsoc': typeof ProGsocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRouteWithChildren
  '/beginner': typeof BeginnerRouteWithChildren
  '/journey': typeof JourneyRoute
  '/pro': typeof ProRouteWithChildren
  '/advanced/dsa': typeof AdvancedDsaRoute
  '/beginner/github': typeof BeginnerGithubRoute
  '/beginner/python': typeof BeginnerPythonRoute
  '/pro/gsoc': typeof ProGsocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRouteWithChildren
  '/beginner': typeof BeginnerRouteWithChildren
  '/journey': typeof JourneyRoute
  '/pro': typeof ProRouteWithChildren
  '/advanced/dsa': typeof AdvancedDsaRoute
  '/beginner/github': typeof BeginnerGithubRoute
  '/beginner/python': typeof BeginnerPythonRoute
  '/pro/gsoc': typeof ProGsocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced'
    | '/beginner'
    | '/journey'
    | '/pro'
    | '/advanced/dsa'
    | '/beginner/github'
    | '/beginner/python'
    | '/pro/gsoc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced'
    | '/beginner'
    | '/journey'
    | '/pro'
    | '/advanced/dsa'
    | '/beginner/github'
    | '/beginner/python'
    | '/pro/gsoc'
  id:
    | '__root__'
    | '/'
    | '/advanced'
    | '/beginner'
    | '/journey'
    | '/pro'
    | '/advanced/dsa'
    | '/beginner/github'
    | '/beginner/python'
    | '/pro/gsoc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedRoute: typeof AdvancedRouteWithChildren
  BeginnerRoute: typeof BeginnerRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  ProRoute: typeof ProRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginner': {
      id: '/beginner'
      path: '/beginner'
      fullPath: '/beginner'
      preLoaderRoute: typeof BeginnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/gsoc': {
      id: '/pro/gsoc'
      path: '/gsoc'
      fullPath: '/pro/gsoc'
      preLoaderRoute: typeof ProGsocRouteImport
      parentRoute: typeof ProRoute
    }
    '/beginner/python': {
      id: '/beginner/python'
      path: '/python'
      fullPath: '/beginner/python'
      preLoaderRoute: typeof BeginnerPythonRouteImport
      parentRoute: typeof BeginnerRoute
    }
    '/beginner/github': {
      id: '/beginner/github'
      path: '/github'
      fullPath: '/beginner/github'
      preLoaderRoute: typeof BeginnerGithubRouteImport
      parentRoute: typeof BeginnerRoute
    }
    '/advanced/dsa': {
      id: '/advanced/dsa'
      path: '/dsa'
      fullPath: '/advanced/dsa'
      preLoaderRoute: typeof AdvancedDsaRouteImport
      parentRoute: typeof AdvancedRoute
    }
  }
}

interface AdvancedRouteChildren {
  AdvancedDsaRoute: typeof AdvancedDsaRoute
}

const AdvancedRouteChildren: AdvancedRouteChildren = {
  AdvancedDsaRoute: AdvancedDsaRoute,
}

const AdvancedRouteWithChildren = AdvancedRoute._addFileChildren(
  AdvancedRouteChildren,
)

interface BeginnerRouteChildren {
  BeginnerGithubRoute: typeof BeginnerGithubRoute
  BeginnerPythonRoute: typeof BeginnerPythonRoute
}

const BeginnerRouteChildren: BeginnerRouteChildren = {
  BeginnerGithubRoute: BeginnerGithubRoute,
  BeginnerPythonRoute: BeginnerPythonRoute,
}

const BeginnerRouteWithChildren = BeginnerRoute._addFileChildren(
  BeginnerRouteChildren,
)

interface ProRouteChildren {
  ProGsocRoute: typeof ProGsocRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProGsocRoute: ProGsocRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedRoute: AdvancedRouteWithChildren,
  BeginnerRoute: BeginnerRouteWithChildren,
  JourneyRoute: JourneyRoute,
  ProRoute: ProRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
